### ISSUE TITLE
Is there a way to declare the usage of this in a compose file?

### ISSUE THREAD

**Issue by nikp123** [lowRISC/container-hotplug#8]
Idea is pretty simple, since we don't want to always override the runtime, can I just specify this project for the compose projects that actually need it. Also is there any difference between podman and docker in that regard?

**Comment by nbdd0121** [comment]
For docker, you should be able to use `runtime`: See https://stackoverflow.com/questions/47465696/how-do-i-specify-nvidia-runtime-from-docker-compose-yml. If you followed the README's setup, it'll be `runtime: hotplug`.

**Comment by nikp123** [comment]
Unrelated, but have you been able to build this as a nix package. Packaging this seems nearly impossible due to how the project is built.

**Comment by nbdd0121** [comment]
Building the BPF component seems a bit difficult, so I just download from releases (built by GitHub Actions on Ubuntu) instead: https://github.com/lowRISC/lowrisc-nix/blob/main/pkgs/container-hotplug/default.nix

**Comment by nikp123** [comment]
> Building the BPF component seems a bit difficult, so I just download from releases (built by GitHub Actions on Ubuntu) instead: https://github.com/lowRISC/lowrisc-nix/blob/main/pkgs/container-hotplug/default.nix

The problem isn't really the eBPF component but linking it to the main project.

**Comment by nikp123** [comment]
> Would you mind sharing your derivation? If you can get bpf part to build then what's left should just be patching
I don't, however, it isn't the cleanest atm.

```nix
{
  description = "A calculator program/website";

  inputs = {
    rust-overlay = {
      url = "github:oxalica/rust-overlay";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, nixpkgs, rust-overlay }:
    let
      systems =
        [ "x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin" ];

      forAllSystems = f: nixpkgs.lib.genAttrs systems (system: f system);

      nixpkgsFor = forAllSystems (system:
        import nixpkgs {
          inherit system;
          overlays = [
            self.overlay 
            rust-overlay.overlays.default
          ];
        });

    in rec {
      overlay = final: prev: let
        rustPlatform = final.makeRustPlatform {
          cargo = final.rust-bin.selectLatestNightlyWith (toolchain: toolchain.default);
          rustc = final.rust-bin.selectLatestNightlyWith (toolchain: toolchain.default);
        };
      in {
        container-hotplug = rustPlatform.buildRustPackage {
          pname = "container-hotplug";
          version = "unstable";
          description = "";

          src = self;

          postPatch = ''
            #rm build.rs
          '';

          nativeBuildInputs = with final; [
            (rust-bin.selectLatestNightlyWith (toolchain: toolchain.default))
            gcc
            udev
            pkg-config
            (pkgs.callPackage deps/bpf-linker.nix { useRustLlvm = false; })
          ];

          #outputs = [ "out" "lib" ];

          #postInstall = ''
          #  moveToOutput "lib" "$lib"
          #'';

          cargoLock = {
            outputHashes = {
              "aya-0.12.0" = "sha256-O7vjnHoHNJxU+W/Cr1JCGprTSDXm4V+rT6x4C4//LGw=";
            };
            lockFile = self + "/Cargo.lock";
          };

          buildInputs = with final; [ udev 
          ];

          #CARGO_FEATURE_USE_SYSTEM_LIBS = "1";
        };
      };

      packages =
        forAllSystems (system: { inherit (nixpkgsFor.${system}) container-hotplug; });

      defaultPackage = forAllSystems (system: self.packages.${system}.container-hotplug);

      apps = forAllSystems (system: {
        container-hotplug = {
          type = "app";
          program = "${self.packages.${system}.container-hotplug}/bin/container-hotplug";
        };
      });

      defaultApp = forAllSystems (system: self.apps.${system}.container-hotplug);

      devShell = forAllSystems (system:
        nixpkgs.legacyPackages.${system}.mkShell {
          inputsFrom = builtins.attrValues (packages.${system});
        });
    };
}
```

**Comment by nikp123** [comment]
<details>
<summary>log</summary>
```
error: failed to run custom build command for `container-hotplug v0.1.0 (/build/source)`

Caused by:
  process didn't exit successfully: `/build/source/target/release/build/container-hotplug-25e29cfb6906f4f6/bu>
  --- stdout
  cargo:rerun-if-changed=cgroup_device_filter/Cargo.lock
  cargo:rerun-if-changed=cgroup_device_filter/Cargo.toml
  cargo:rerun-if-changed=cgroup_device_filter/rust-toolchain.toml
  cargo:rerun-if-changed=cgroup_device_filter/.cargo/config.toml
  cargo:rerun-if-changed=cgroup_device_filter/src/main.rs

  --- stderr
  warning: `/build/.cargo/config` is deprecated in favor of `config.toml`
  note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
  error: no matching package found
  searched package name: `aya-ebpf`
  perhaps you meant:      aya-obj
  location searched: directory source `/build/cargo-vendor-dir` (which is replacing https://github.com/aya-rs>
  required by package `cgroup_device_filter v0.1.0 (/build/source/cgroup_device_filter)`
  Error: Failed to build eBPF program
warning: build failed, waiting for other jobs to finish...
lines 77-124/124 (END)
```
</details>

**Comment by nikp123** [comment]
I could hack around this by importing the cgroup binary's rust deps into the main project

**Comment by nbdd0121** [comment]
I think you'd probably need to have two buildRustPackage, one for the eBPF cgroup binary and another for the main one.

**Comment by nikp123** [comment]
> I think you'd probably need to have two buildRustPackage, one for the eBPF cgroup binary and another for the main one.

Tried already and it fails because cfg-if is missing from the toml file. I can leave you with what i had last but I'm not sure how to fix it.

**Comment by nikp123** [comment]
Back on topic, this may sound like a stupid question, but where do I specify the runtime for podman containers? (Besides the direct command-line flag)

I haven't had found any information on how to set the runtime without making it the default.
```ini
[engine]
runtime = /usr/bin/....
```

**Comment by nbdd0121** [comment]
If you use nix this should work:

```nix
virtualisation.containers.containersConf.settings.engine.runtime.hotplug = ["path"];
```

**Comment by nikp123** [comment]
> virtualisation.containers.containersConf.settings.engine.runtimes.hotplug = ["path"];

This seems incorrect, I am trying ```virtualisation.containers.containersConf.settings.engine.runtimes.hotplug.path = ["binary_path"];```

**Comment by nbdd0121** [comment]
It should be the correct format, see https://github.com/containers/common/blob/ebbd7f3c7746687329b77bd9857f0eba499ee2d9/pkg/config/containers.conf#L793

**Comment by nikp123** [comment]
> It should be the correct format, see https://github.com/containers/common/blob/ebbd7f3c7746687329b77bd9857f0eba499ee2d9/pkg/config/containers.conf#L793

Sorry, my bad, I forgot to turn it into a list before specifying the path.

**Comment by nikp123** [comment]
Thanks for all the help. Sorry I couldn't get the nix package to run though, the compilation pipeline on this one is quite a mess.
